export enum ReportElementState {
    RENDER_TEST = "RENDER_TEST",
    IDLE = "IDLE",
    GENERAL_TEST = "GENERAL_TEST",
    TESTING_CHILD = "TESTING_CHILD",
    SLICING = "SLICING",
    FINISHING = "FINISHING",
    FINISHED = "FINISHED"
}